name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4 # Action to deploy to GitHub Pages
        with:
          branch: gh-pages  # Target branch for deployment
          folder: .  # The folder where the static files are located (using root folder)
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
